### PR TITLE
fix: format Hudi config enum should show the full config key

### LINKED ISSUE #253: Hudi Config formatted in string should show the full config key
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the bug

`format!("{}", HudiTableConfig::KeyGeneratorClass)` should show `hoodie.table.keygenerator.class` instead of `KeyGeneratorClass`

### Steps To Reproduce

Run `format!()`

### Expected behavior

Show full config key

### Screenshots / Logs

_No response_

### Software information

NA

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Kunal-Singh-Dadhwal**
## Description

1. Implemented display trait for the HudiTableConfig
2. Added Test 

Closes #253 

## How are the changes test-covered

- [ ] N/A
- [x] Automated tests (unit and/or integration tests)
- [ ] Manual tests
  - [ ] Details are described below

### CODE REVIEW

File: crates/core/src/config/table.rs [hunk 1]
```diff
@@ -141,6 +141,12 @@ impl AsRef<str> for HudiTableConfig {
     }
 }
 
+impl Display for HudiTableConfig {
```
Comment (xushiyan) [inline crates/core/src/config/table.rs:144]: you probably need to do this for other config categories as well.

Comment (Kunal-Singh-Dadhwal) [reply crates/core/src/config/table.rs:144]: Done it for all the config categories

**Review by xushiyan — APPROVED** [review]

**Comment by xushiyan** [comment]
@Kunal-Singh-Dadhwal thanks for the PR!
